version: '3.8'

services:
  films-api:
    image: films-api
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8.0
    container_name: films-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admintorugo
      MYSQL_DATABASE: filmsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data: